version: '3'

services:
  pgsql:
    image: postgres:alpine
    ports:
      - '5432:5432'
    container_name: 'pgsql'
    restart: always
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres_auth
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    volumes:
      - /var/lib/postgresql/data
  
 # nginx:
 #  image: nginx
 #  restart: always
 #  ports:
 #    - 3030:80
 #  volumes:
 #    - ./nginx:/etc/nginx/
 #    - ./images:/data/images